[toolchain]
channel = "nightly"
targets = [
	"x86_64-unknown-linux-gnu",
	"x86_64-pc-windows-msvc",
	"aarch64-linux-android",
	"armv7-linux-androideabi",
	"i686-linux-android",
	"x86_64-linux-android",
	"wasm32-unknown-unknown"
]
